const usernames = [
    'Aaran',
    'Aaren',
    'Aarez',
    'Aarman',
    'Aaron',
    'Aaron-James',
    'Aarron',
    'Aaryan',
    'Aaryn',
    'Aayan',
    'Aazaan',
    'Abaan',
    'Abbas',
    'Abdallah',
    'Abdalroof',
    'Abdihakim',
    'Abdirahman',
    'Abdisalam',
    'Abdul',
    'Abdul-Aziz',
    'Abdulbasir',
    'Abdulkadir',
    'Abdulkarem',
    'Smith',
    'Jones',
    'Coollastname',
    'enter_name_here',
    'Ze',
    'Zechariah',
    'Zeek',
    'Zeeshan',
    'Zeid',
    'Zein',
    'Zen',
    'Zendel',
    'Zenith',
    'Zennon',
    'Zeph',
    'Zerah',
    'Zhen',
    'Zhi',
    'Zhong',
    'Zhuo',
    'Zi',
    'Zidane',
    'Zijie',
    'Zinedine',
    'Zion',
    'Zishan',
    'Ziya',
    'Ziyaan',
    'Zohaib',
    'Zohair',
    'Zoubaeir',
    'Zubair',
    'Zubayr',
    'Zuriel',
    'Xander',
    'Jared',
    'Courtney',
    'Gillian',
    'Clark',
    'Jared',
    'Grace',
    'Kelsey',
    'Tamar',
    'Alex',
    'Mark',
    'Tamar',
    'Farish',
    'Sarah',
    'Nathaniel',
    'Parker',
  ];
  
  const thoughtText = [
    'Great movie!',
    'Really liked it!',
    'It was terrible.',
    'Do not buy :(',
    'I thought it was okay.',
    'LIFE CHANGING!!!',
    'One of the best books I ever read.',
    'This electric toothbrush works great.',
    'Daft Punk is my favorite band.',
    'Beautiful art!',
    'You are so talented!',
    'I love to program websites.',
    'Class was so great!',
    'I am training for a marathon.',
    'I hate running.',
    'I love banana bread.',
    'Have you ever had random thoughts?',
    'The Ninja Turtles are rad.',
  ];
  
  // Get a random item given an array
  const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];
  
  // Gets a random username
  const getRandomName = () =>
    `${getRandomArrItem(usernames)}`;
  
  // Function to generate random thoughts that we can add to user object.
  const getRandomThoughts = () =>
  `${getRandomArrItem(thoughtText)}`;
  
  // Export the functions for use in seed.js
  module.exports = { getRandomName, getRandomThoughts };
  